# -*- coding: utf-8 -*-
"""Cobamf1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_WsUrXHDMKrNj-LHd2M6KNoHqkPG90_p
"""

import streamlit as st

st.title("MATCH FACTOR")

st.write("=" * 20)

JumlahHD = st.number_input("Masukkan Jumlah HD:", value=0.0)
Serving = st.number_input("Masukkan Waktu Serving:", value=0.0)
CTHD = st.number_input("Masukkan CTHD:", value=0.0)

hasil = (JumlahHD * Serving) / CTHD

st.write(f"Hasilnya adalah {hasil}")

if hasil >= 1:
    st.write("HD pasti Ngantri")
else:
    st.write("PC gantung ya")